cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from . import views, webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

payment/views.py
from decimal import Decimal
from http import HTTPStatus

import stripe
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render, reverse

from orders.models import Order

# создать экземпляр Stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        # данные сеанса оформления платежа Stripe
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        # добавить товарные позиции заказа
        # в сеанс оформления платежа Stripe
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'rub',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })
        # купон Stripe
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon.code,
                percent_off=order.discount,
                duration='once')
            session_data['discounts'] = [{
                'coupon': stripe_coupon.id
            }]
        # создать сеанс оформления платежа Stripe
        session = stripe.checkout.Session.create(**session_data)
        # перенаправить к форме для платежа Stripe
        return redirect(session.url, code=HTTPStatus.MOVED_PERMANENTLY)
    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends "shop/base.html" %}
{% block title %}Платеж отменен{% endblock %}
{% block content %}
    <h1>Ваш платеж не был обработан</h1>
    <p>Возникла проблема с обработкой вашего платежа.</p>
{% endblock %}

payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% block title %}Платеж прошел успешно{% endblock %}
{% block content %}
    <h1>Ваш платеж прошел успешно</h1>
    <p>Ваш платеж был успешно обработан.</p>
{% endblock %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Список покупок{% endblock %}
{% block content %}
    <h1>Сумма заказа</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Цена</th>
            <th>Количество</th>
            <th>Сумма</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle "1" "2" %}">
                <td>
                    <img src="
                    {% if item.product.image %}
                        {{ item.product.image.url }}
                    {% else %}
                        {% static "img/no_image.png" %}
                    {% endif %}
                    ">
                </td>
                <td>{{ item.product.name }}</td>
                <td class="num">&#8381; {{ item.price }}</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">&#8381; {{ item.get_cost }}</td>
            </tr>
        {% endfor %}
        {% if order.coupon %}
            <tr class="subtotal">
                <td>Промежуточный итог</td>
                <td colspan="3"></td>
                <td class="num">
                    &#8381;{{ order.get_total_cost_before_discount|floatformat:2 }}
                </td>
            </tr>
            <tr>
                <td>
                    "{{ order.coupon.code }}" купон
                    ({{ order.discount }}% скидка)
                </td>
                <td colspan="3"></td>
                <td class="num neg">
                    – &#8381;{{ order.get_discount|floatformat:2 }}
                </td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>Сумма</td>
            <td colspan="3"></td>
            <td class="num">
                &#8381;{{ order.get_total_cost|floatformat:2 }}
            </td>
        </tr>

        </tbody>
    </table>
    <form action="{% url "payment:process" %}" method="post">
        <input type="submit" value="Оплатить заказ">
        {% csrf_token %}
    </form>
{% endblock %}